services:
  wordpress:
    image: wordpress:6.8.2-php8.3-apache
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: jkroyston
      WORDPRESS_DB_PASSWORD: bFlSm9slw
      WORDPRESS_DB_NAME: jkaltrocks_db
    volumes:
      - ./wp-content:/var/www/html/wp-content
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: jkaltrocks_db
      MYSQL_USER: jkroyston
      MYSQL_PASSWORD: bFlSm9slw
      MYSQL_RANDOM_ROOT_PASSWORD: 'root'
    volumes:
      - wp_data:/var/lib/mysql

volumes:
  wp_data: